blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a general GRC question
    url: https://discord.studygrc.org
    about: Join our Discord server to ask questions, debate policies, and hang out with the community!
